using System.ComponentModel.DataAnnotations;
using Backend.commons;

namespace Backend.DTOs;

public record MemberCreateDTO(
    [Required][StringLength(50, MinimumLength = 2)] string FirstName,
    [StringLength(50)] string? SecondName,
    [StringLength(50, MinimumLength = 2)] string? LastName,
    [StringLength(50)] string? SecondLastName,
    [Required] Gender Gender,
    [Required] DateTime BirthDate,
    [Required] MaritalStatus MaritalStatus,
    [StringLength(20)] string? NationalId,
    [StringLength(20)] string? PassportNumber,
    [StringLength(50)] string? BirthPlace,
    [StringLength(50)] string? Nationality,
    string? PhotoUrl,
    [Phone][StringLength(15)] string? PhoneNumber,
    [EmailAddress][StringLength(150)] string? Email,
    string? Address,
    int? SectorId,
    [StringLength(100)] string? EmergencyContactName,
    [StringLength(15)] string? EmergencyContactPhone,
    int? FamilyId,
    string? MedicalCondition,
    [StringLength(5)] string? BloodType,
    MemberType? MemberType,
    DateTime? JoinDate,
    DateTime? ConversionDate,
    [StringLength(100)] string? OriginChurch,
    bool Baptized,
    DateTime? BaptismDate,
    [StringLength(100)] string? BaptismPlace,
    [StringLength(50)] string? DiscipleshipLevel,
    int? SmallGroupId,
    int? ChurchRoleId,
    string? MemberSkills,
    bool Discipline,
    bool CourtCase,
    AcademicLevel? AcademicLevel,
    [StringLength(100)] string? Profession,
    [StringLength(100)] string? Occupation,
    string? MemberCourses
);

public record MemberResponseDTO(
    int MemberId,
    string FirstName,
    string? SecondName,
    string? LastName,
    string? SecondLastName,
    Gender Gender,
    DateTime BirthDate,
    MaritalStatus MaritalStatus,
    string? NationalId,
    string? PassportNumber,
    string? BirthPlace,
    string? Nationality,
    string? PhotoUrl,
    string? PhoneNumber,
    string? Email,
    string? Address,
    int? SectorId,
    string? EmergencyContactName,
    string? EmergencyContactPhone,
    int? FamilyId,
    string? MedicalCondition,
    string? BloodType,
    MemberType? MemberType,
    DateTime? JoinDate,
    DateTime? ConversionDate,
    string? OriginChurch,
    bool Baptized,
    DateTime? BaptismDate,
    string? BaptismPlace,
    string? DiscipleshipLevel,
    int? SmallGroupId,
    int? ChurchRoleId,
    string? MemberSkills,
    bool Discipline,
    bool CourtCase,
    AcademicLevel? AcademicLevel,
    string? Profession,
    string? Occupation,
    string? MemberCourses,
    DateTime? CreatedAt,
    DateTime? UpdatedAt
);

public record MemberUpdateDTO(
    [Required][StringLength(50, MinimumLength = 2)] string FirstName,
    [StringLength(50)] string? SecondName,
    [StringLength(50, MinimumLength = 2)] string? LastName,
    [StringLength(50)] string? SecondLastName,
    [Required] Gender Gender,
    [Required] DateTime BirthDate,
    [Required] MaritalStatus MaritalStatus,
    [StringLength(20)] string? NationalId,
    [StringLength(20)] string? PassportNumber,
    [StringLength(50)] string? BirthPlace,
    [StringLength(50)] string? Nationality,
    string? PhotoUrl,
    [Phone][StringLength(15)] string? PhoneNumber,
    [EmailAddress][StringLength(150)] string? Email,
    string? Address,
    int? SectorId,
    [StringLength(100)] string? EmergencyContactName,
    [StringLength(15)] string? EmergencyContactPhone,
    int? FamilyId,
    string? MedicalCondition,
    [StringLength(5)] string? BloodType,
    MemberType? MemberType,
    DateTime? JoinDate,
    DateTime? ConversionDate,
    [StringLength(100)] string? OriginChurch,
    bool Baptized,
    DateTime? BaptismDate,
    [StringLength(100)] string? BaptismPlace,
    [StringLength(50)] string? DiscipleshipLevel,
    int? SmallGroupId,
    int? ChurchRoleId,
    string? MemberSkills,
    bool Discipline,
    bool CourtCase,
    AcademicLevel? AcademicLevel,
    [StringLength(100)] string? Profession,
    [StringLength(100)] string? Occupation,
    string? MemberCourses
);
